# Because GH actions sucks we can't have anchors therefore pls run this command to generate actions script
# Please edit release.yaml.template instead of release.yaml and then run this command
# Cmd: yq eval 'explode(.)' .\release.yaml.template > release.yaml
# Tool installation docs: https://mikefarah.gitbook.io/yq/#install
on:
  push:
    branches:
      - main
  release:
    types:
      - published
jobs:
  update_readme:
    name: "Update Readme"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "main"
      - uses: actions/cache@v1
        with:
          path: |
            tools/.gradle/caches
            tools/build
            tools/readme_generator/.gradle/caches
            tools/readme_generator/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Java JDK 16
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: 16
      - name: Gradle (RUN)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd tools && gradle :readme_generator:run
      - name: Update Readme file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README.md
          commit_author: Michael Rittmeister <michael@rittmeister.in>
          file_pattern: README.md
  jdk16:
    name: "Build on JDK 16"
    runs-on: ubuntu-20.04
    if: "github.event_name == 'release'"
    env:
      JDK_TAG: 16
      ROOT_TAG: true
      GHCR_PASSWORD: ${{ secrets.GHCR_PASSWORD }}
      GHCR_ACCOUNT: ${{ secrets.GHCR_ACCOUNT }}
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Build Oracle
        env:
          KOTLIN_VERSION: ${{ steps.get_version.outputs.VERSION }}
          ADDITIONAL_TAG: ${{ steps.get_version.outputs.VERSION}}
          TAG: "${{ steps.get_version.outputs.VERSION }}-jdk${{env.JDK_TAG}}"
          DOCKER_ACCOUNT: ${{ secrets.DOCKER_ACCOUNT }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMPILER_URL: "https://github.com/JetBrains/kotlin/releases/download/v${{ steps.get_version.outputs.VERSION }}/kotlin-compiler-${{ steps.get_version.outputs.VERSION }}.zip"
          SOURCE: "openjdk:${{env.JDK_TAG}}-oracle"
          BUILD_CONTEXT: "oracle"
        run: "scripts/build.sh"
      - name: Build with Debian
        env:
          KOTLIN_VERSION: ${{ steps.get_version.outputs.VERSION }}
          DOCKER_ACCOUNT: ${{ secrets.DOCKER_ACCOUNT }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMPILER_URL: "https://github.com/JetBrains/kotlin/releases/download/v${{ steps.get_version.outputs.VERSION }}/kotlin-compiler-${{ steps.get_version.outputs.VERSION }}.zip"
          ADDITIONAL_TAG: "${{ steps.get_version.outputs.VERSION }}-debian"
          TAG: "${{ steps.get_version.outputs.VERSION }}-jdk${{env.JDK_TAG}}-debian"
          SOURCE: "adoptopenjdk/openjdk${{env.JDK_TAG}}:debian"
          BUILD_CONTEXT: "debian"
        run: "scripts/build.sh"
      - name: Build with Alpine
        env:
          KOTLIN_VERSION: ${{ steps.get_version.outputs.VERSION }}
          DOCKER_ACCOUNT: ${{ secrets.DOCKER_ACCOUNT }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMPILER_URL: "https://github.com/JetBrains/kotlin/releases/download/v${{ steps.get_version.outputs.VERSION }}/kotlin-compiler-${{ steps.get_version.outputs.VERSION }}.zip"
          ADDITIONAL_TAG: "${{ steps.get_version.outputs.VERSION }}-alpine"
          SOURCE: "adoptopenjdk/openjdk${{env.JDK_TAG}}:alpine"
          TAG: "${{ steps.get_version.outputs.VERSION }}-jdk${{env.JDK_TAG}}-alpine"
          BUILD_CONTEXT: "alpine"
        run: "scripts/build.sh"
      - name: Build slim
        env:
          KOTLIN_VERSION: ${{ steps.get_version.outputs.VERSION }}
          DOCKER_ACCOUNT: ${{ secrets.DOCKER_ACCOUNT }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMPILER_URL: "https://github.com/JetBrains/kotlin/releases/download/v${{ steps.get_version.outputs.VERSION }}/kotlin-compiler-${{ steps.get_version.outputs.VERSION }}.zip"
          ADDITIONAL_TAG: "${{ steps.get_version.outputs.VERSION }}-slim"
          SOURCE: "adoptopenjdk/openjdk${{env.JDK_TAG}}:alpine-slim"
          TAG: "${{ steps.get_version.outputs.VERSION }}-jdk${{env.JDK_TAG}}-slim"
          BUILD_CONTEXT: "slim"
        run: "scripts/build.sh"
  jdk11:
    name: "Build on JDK 11"
    runs-on: ubuntu-20.04
    if: "github.event_name == 'release'"
    env:
      ROOT_TAG: false
      JDK_TAG: 11
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Build Oracle
        env:
          KOTLIN_VERSION: ${{ steps.get_version.outputs.VERSION }}
          ADDITIONAL_TAG: ${{ steps.get_version.outputs.VERSION}}
          TAG: "${{ steps.get_version.outputs.VERSION }}-jdk${{env.JDK_TAG}}"
          DOCKER_ACCOUNT: ${{ secrets.DOCKER_ACCOUNT }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMPILER_URL: "https://github.com/JetBrains/kotlin/releases/download/v${{ steps.get_version.outputs.VERSION }}/kotlin-compiler-${{ steps.get_version.outputs.VERSION }}.zip"
          SOURCE: "openjdk:${{env.JDK_TAG}}-oracle"
          BUILD_CONTEXT: "oracle"
        run: "scripts/build.sh"
      - name: Build with Debian
        env:
          KOTLIN_VERSION: ${{ steps.get_version.outputs.VERSION }}
          DOCKER_ACCOUNT: ${{ secrets.DOCKER_ACCOUNT }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMPILER_URL: "https://github.com/JetBrains/kotlin/releases/download/v${{ steps.get_version.outputs.VERSION }}/kotlin-compiler-${{ steps.get_version.outputs.VERSION }}.zip"
          ADDITIONAL_TAG: "${{ steps.get_version.outputs.VERSION }}-debian"
          TAG: "${{ steps.get_version.outputs.VERSION }}-jdk${{env.JDK_TAG}}-debian"
          SOURCE: "adoptopenjdk/openjdk${{env.JDK_TAG}}:debian"
          BUILD_CONTEXT: "debian"
        run: "scripts/build.sh"
      - name: Build with Alpine
        env:
          KOTLIN_VERSION: ${{ steps.get_version.outputs.VERSION }}
          DOCKER_ACCOUNT: ${{ secrets.DOCKER_ACCOUNT }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMPILER_URL: "https://github.com/JetBrains/kotlin/releases/download/v${{ steps.get_version.outputs.VERSION }}/kotlin-compiler-${{ steps.get_version.outputs.VERSION }}.zip"
          ADDITIONAL_TAG: "${{ steps.get_version.outputs.VERSION }}-alpine"
          SOURCE: "adoptopenjdk/openjdk${{env.JDK_TAG}}:alpine"
          TAG: "${{ steps.get_version.outputs.VERSION }}-jdk${{env.JDK_TAG}}-alpine"
          BUILD_CONTEXT: "alpine"
        run: "scripts/build.sh"
      - name: Build slim
        env:
          KOTLIN_VERSION: ${{ steps.get_version.outputs.VERSION }}
          DOCKER_ACCOUNT: ${{ secrets.DOCKER_ACCOUNT }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMPILER_URL: "https://github.com/JetBrains/kotlin/releases/download/v${{ steps.get_version.outputs.VERSION }}/kotlin-compiler-${{ steps.get_version.outputs.VERSION }}.zip"
          ADDITIONAL_TAG: "${{ steps.get_version.outputs.VERSION }}-slim"
          SOURCE: "adoptopenjdk/openjdk${{env.JDK_TAG}}:alpine-slim"
          TAG: "${{ steps.get_version.outputs.VERSION }}-jdk${{env.JDK_TAG}}-slim"
          BUILD_CONTEXT: "slim"
        run: "scripts/build.sh"
  jdk8:
    name: "Build on JDK 1.8"
    runs-on: ubuntu-20.04
    if: "github.event_name == 'release'"
    env:
      ROOT_TAG: false
      JDK_TAG: 8
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Build Oracle
        env:
          KOTLIN_VERSION: ${{ steps.get_version.outputs.VERSION }}
          ADDITIONAL_TAG: ${{ steps.get_version.outputs.VERSION}}
          TAG: "${{ steps.get_version.outputs.VERSION }}-jdk${{env.JDK_TAG}}"
          DOCKER_ACCOUNT: ${{ secrets.DOCKER_ACCOUNT }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMPILER_URL: "https://github.com/JetBrains/kotlin/releases/download/v${{ steps.get_version.outputs.VERSION }}/kotlin-compiler-${{ steps.get_version.outputs.VERSION }}.zip"
          SOURCE: "openjdk:${{env.JDK_TAG}}-oracle"
          BUILD_CONTEXT: "oracle"
        run: "scripts/build.sh"
      - name: Build with Debian
        env:
          KOTLIN_VERSION: ${{ steps.get_version.outputs.VERSION }}
          DOCKER_ACCOUNT: ${{ secrets.DOCKER_ACCOUNT }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMPILER_URL: "https://github.com/JetBrains/kotlin/releases/download/v${{ steps.get_version.outputs.VERSION }}/kotlin-compiler-${{ steps.get_version.outputs.VERSION }}.zip"
          ADDITIONAL_TAG: "${{ steps.get_version.outputs.VERSION }}-debian"
          TAG: "${{ steps.get_version.outputs.VERSION }}-jdk${{env.JDK_TAG}}-debian"
          SOURCE: "adoptopenjdk/openjdk${{env.JDK_TAG}}:debian"
          BUILD_CONTEXT: "debian"
        run: "scripts/build.sh"
      - name: Build with Alpine
        env:
          KOTLIN_VERSION: ${{ steps.get_version.outputs.VERSION }}
          DOCKER_ACCOUNT: ${{ secrets.DOCKER_ACCOUNT }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMPILER_URL: "https://github.com/JetBrains/kotlin/releases/download/v${{ steps.get_version.outputs.VERSION }}/kotlin-compiler-${{ steps.get_version.outputs.VERSION }}.zip"
          ADDITIONAL_TAG: "${{ steps.get_version.outputs.VERSION }}-alpine"
          SOURCE: "adoptopenjdk/openjdk${{env.JDK_TAG}}:alpine"
          TAG: "${{ steps.get_version.outputs.VERSION }}-jdk${{env.JDK_TAG}}-alpine"
          BUILD_CONTEXT: "alpine"
        run: "scripts/build.sh"
      - name: Build slim
        env:
          KOTLIN_VERSION: ${{ steps.get_version.outputs.VERSION }}
          DOCKER_ACCOUNT: ${{ secrets.DOCKER_ACCOUNT }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMPILER_URL: "https://github.com/JetBrains/kotlin/releases/download/v${{ steps.get_version.outputs.VERSION }}/kotlin-compiler-${{ steps.get_version.outputs.VERSION }}.zip"
          ADDITIONAL_TAG: "${{ steps.get_version.outputs.VERSION }}-slim"
          SOURCE: "adoptopenjdk/openjdk${{env.JDK_TAG}}:alpine-slim"
          TAG: "${{ steps.get_version.outputs.VERSION }}-jdk${{env.JDK_TAG}}-slim"
          BUILD_CONTEXT: "slim"
        run: "scripts/build.sh"
