on:
  schedule:
    - cron: "0 * * * *"

jobs:
  run:
    name: "Check for new Kotlin releases"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "main"
      - name: Setup Java JDK 16
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: 16
      - uses: gradle/gradle-build-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build-root-directory: ./tools
          arguments: :release_notifier:run
      - name: Prepare git to sign commit
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true
      - name: Update Previous file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update checked Kotlin version store
          commit_options: '-S' # sign commit
          commit_author: Michael Rittmeister <michael@rittmeister.in>
          file_pattern: tools/release_notifier/checked_versions.json
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "Kotlin Release:"
          draft: true
          tag_name: v${{ needs.build_metadata.outputs.version }}
          release_name: ${{ needs.build_metadata.outputs.version }}
